### ISSUE TITLE
Role fails due to oracle-java8-installer unavailability

### ISSUE THREAD

**Issue by Madnessy** [Graylog2/graylog-ansible-role#106]
Role fails on ubuntu 16.04 with this message :
```
TASK [Graylog2.graylog-ansible-role : Java 8 should be installed] **************************************************************************
fatal: [graylog01]: FAILED! => {"changed": false, "msg": "No package matching 'oracle-java8-installer' is available"}
```

according to the installation manual it's not even required ?
http://docs.graylog.org/en/2.4/pages/installation/os/ubuntu.html

**Comment by Madnessy** [comment]
Well this isnt fixed cause my pr is declined.
Is there any eta on the "new" ansible playbook ?

**Comment by CVirus** [comment]
Try this instead:
`java_packages:
  - openjdk-8-jre-headless`

**Comment by Madnessy** [comment]
well either i do not install java using the graylog role or use a fork which allows to install openjdk.
Cause the java package is hard coded  in the task file:
https://github.com/Graylog2/graylog-ansible-role/blob/e944232eddd6b6f22a29da98c1223eda1bc2a246/tasks/java-Debian.yml#L36-L39

**Comment by CVirus** [comment]
> well either i do not install java using the graylog role or use a fork which allows to install openjdk.
> Cause the java package is hard coded in the task file:
> https://github.com/Graylog2/graylog-ansible-role/blob/e944232eddd6b6f22a29da98c1223eda1bc2a246/tasks/java-Debian.yml#L36-L39

https://github.com/Graylog2/graylog-ansible-role/blob/b8ebd17d2ac83f5d400d7197b20bf4372d6df416/README.md

**Comment by CVirus** [comment]
> well either i do not install java using the graylog role or use a fork which allows to install openjdk.
> Cause the java package is hard coded in the task file:
> https://github.com/Graylog2/graylog-ansible-role/blob/e944232eddd6b6f22a29da98c1223eda1bc2a246/tasks/java-Debian.yml#L36-L39

You're right.

The readme shows an example on how to do that https://github.com/Graylog2/graylog-ansible-role/blob/master/README.md#details-to-avoid-issues-with-java-install-behind-proxy-use-openjdk

**Comment by juju2112** [comment]
I updated the role to use `lean_delivery.java` when `graylog_install_java` is True. It looks way more flexible. 

https://github.com/lean-delivery/ansible-role-java
