### ISSUE TITLE
Typo in graylog_mongodb_debain_key: debain vs debian

### ISSUE THREAD

**Issue by mika** [Graylog2/graylog-ansible-role#110]
It's `graylog_mongodb_debain_key` in `defaults/main.yml` and `tasks/mongodb-Debian.yml`, instead of `graylog_mongodb_debian_key` (`debain` vs `debian`).

The change to fix this itself is trivial, I am not sure about requirements for backwards compatibility though?

**Comment by slackware666** [comment]
@mika I fixed this, thanks!
