### ISSUE TITLE
[graylog3.x] graylog_http_publish_uri default settings cause log spam 

### ISSUE THREAD

**Issue by jrunu** [Graylog2/graylog-ansible-role#113]
According to the documentation for http_publish_uri the wildcard address 0.0.0.0 is only permissable if set via $http_bind_address. Which is the default if http_publish_uri remains unset. For default in the role http_publish_uri is set to "http://0.0.0.0:9000" which is an invalid value. The graylog-server defaults to the, probably first, non-loopback ipv4 address, however it logs this fact every second.

In the default scenario also the "Wait for graylog server to start up" tasks fails. 

I'm not 100% positive what the best course of action would be. The template statements could be guarded with conditionals to only add these lines if the variable is set. Thus it defaults to the graylog documented behavior. The liveliness check could use the ansible host if the graylog_http_publish_uri was not set.

**Comment by juju2112** [comment]
Yeah, I saw this, too. In the tests, I set it to the IP address of the VM. That seemed to make the errors go away.

https://github.com/Graylog2/graylog-ansible-role/blob/master/molecule/default/converge.yml#L13-L15

@mariussturm What's the best value to set these defaults to?
