### ISSUE TITLE
Many deprecation warnings with current ansible version

### ISSUE THREAD

**Issue by sjwk** [Graylog2/graylog-ansible-role#117]
Running the role with the current stable version of ansible gives a number of deprecation warnings, some of which for behaviour which is due to be removed in the next release.  Some examples:

`TASK [graylog2.graylog-ansible-role : Package 'apt-transport-https' should be installed] ***
[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present'
instead.. This feature will be removed in version 2.9. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
`

`TASK [graylog2.graylog-ansible-role : Ensure Java is installed] ****************
[DEPRECATION WARNING]: evaluating graylog_install_java as a bare variable, this
 behaviour will go away and you might need to add |bool to the expression in
the future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature
will be removed in version 2.12. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
`

`TASK [graylog2.graylog-ansible-role : Discover systemd capabilities] ***********
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|version_compare` use `result is version_compare`. This feature will be
removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
`

**Comment by L1ghtn1ng** [comment]
From what I have seen this is due to the elasticsearch role and not graylog role so it is a different upstream issue

**Comment by danielmorlock** [comment]
> From what I have seen this is due to the elasticsearch role and not graylog role so it is a different upstream issue

I don't think so: `graylo2.graylog-ansible-role` requires `elastic.elasticsearch-6.6.0` as dependency which inherits deprecated filter i.e. `version_compare`. So with recent ansible `2.9+` this role cannot be used as is.

**Comment by danielmorlock** [comment]
The task "Discover systemd capabilities" of role `graylog-ansible-role` is also using the deprecated `version_compare` filter.

**Comment by danielmorlock** [comment]
I just found out that this is already addresses here https://github.com/Graylog2/graylog-ansible-role/commit/0ca1c6b35071697319cda05482348a4619d0188a.

**Comment by juju2112** [comment]
I believe this is all updated now.
