### ISSUE TITLE
Ubuntu - No Graylog servers available. Cannot log in.

### ISSUE THREAD

**Issue by sebastienbonami** [Graylog2/graylog-ansible-role#13]
Hi, I can't get this role to work on a Ubuntu machine. I use the **Quickstart** and the **More detailed example** configuration from the README. 

At first, I was getting an error in MongoDB installation, but I fixed it (see my pull request here: https://github.com/lesmyrmidons/ansible-role-mongodb/pull/2). 

Now, I have no error when running my playbook, but when I want to log in to Graylog web interface, I have this following error:
``No Graylog servers available. Cannot log in.``

When I click **Check server connections**:
``The web interface was unable to connect to any Graylog node in the cluster so far.``
``Please check that the configured nodes shown on the left hand side are correct and that the servers are reachable.``

In **Configured nodes**:
 ``http://127.0.0.1:12900``
 ``Never connected!``

Thanks for your help.

**Comment by mariussturm** [comment]
Sorry can not reproduce this. The Ansible role works as expected for me and all services are running fine. Do you have enough RAM on the machine to serve all services? 4Gb should be fine.

**Comment by chhantyal** [comment]
Hi @mariussturm , I think this is valid bug. I am also getting exact same error. 
I am trying to setup on virtual server, does that have anything to do with it?

My system details: 
Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-45-generic x86_64)
RAM 4GB
CPU 2x cores

**Comment by chhantyal** [comment]
Looks like this is ES dependency version issue https://twitter.com/_lennart/status/637697927566200832?

**Comment by sebastienbonami** [comment]
@chhantyal I tried ES 1.6 instead of the default 1.5 and this solved the problem. I simply set the var *elasticsearch_version: '1.6'* in the playbook.

@mariussturm The README should be updated accordingly. The default Graylog package is setted to 1.1 and ES 1.6 at least is needed.

**Comment by mariussturm** [comment]
Thanks for the report! I have add a note to the examples that you should install ES 1.7 for latest Graylog.

**Comment by chhantyal** [comment]
@mariussturm Thanks for the update. Can we not use `f500/ansible-elasticsearch` as dependency in that case? It installs ES 1.5 https://github.com/f500/ansible-elasticsearch/blob/master/defaults/main.yml

**Comment by mariussturm** [comment]
@chhantyal yes, thats the configured dependency: https://github.com/Graylog2/graylog-ansible-role/blob/master/requirements.yml#L3
But ES 1.5 is not recommened, simply add `elasticsearch_version: '1.7'` to your `playbook.yml`

**Comment by munirathnam** [comment]
Guys, Please ensure you stop the graylog web and Start again..It works!!!
