### ISSUE TITLE
Embedded or external ElasticSearch? Embedded or external webserver?

### ISSUE THREAD

**Issue by varnav** [Graylog2/graylog-ansible-role#14]
Hello! Looks like this playbook configures embedded ElasticSearch, but at same time it installs external ElasticSearch as a dependency. Is that correct?

Also I've been using Graylog without any webserver (it has embedded one I believe) - are there any benefits from using nginx instead?

**Comment by mariussturm** [comment]
What du you mean by embedded Elasticsearch?
The playbook should install Elasticsearch as a dependency on the same host as Graylog-server. Do you see any different behaviour?

**Comment by jamescarr** [comment]
I think he is referring to the embedded elasticsearch included in graylog-server

**Comment by mariussturm** [comment]
The Graylog server comes with a build-in Elasticsearch client library. It acts like a ES node to talk to the remaining cluster. With the only exception that the Graylog server never stores any data. This is always handled by the real ES nodes. But there is no alternative way of communicating to the ES cluster. So we always have to configure it. Take a look into the Graylog server config, there are settings with a `elasticsearch_` prefix.
