### ISSUE TITLE
install graylog-ansible-role role fails on elastic.elasticsearch role

### ISSUE THREAD

**Issue by danvac** [Graylog2/graylog-ansible-role#141]
vdanek@mother ansible]$ ansible-galaxy install graylog2.graylog-ansible-role
- downloading role 'graylog-ansible-role', owned by graylog2
- downloading role from https://github.com/Graylog2/graylog-ansible-role/archive/3.0.1.tar.gz
- extracting graylog2.graylog-ansible-role to /home/vdanek/.ansible/roles/graylog2.graylog-ansible-role
- graylog2.graylog-ansible-role (3.0.1) was installed successfully
- adding dependency: elastic.elasticsearch
- adding dependency: jdauphant.nginx
- downloading role 'elasticsearch', owned by elastic
[WARNING]: - elastic.elasticsearch was NOT installed successfully: Unable to compare role versions (0.1.1, 0.1.2,
5.5.1, 6.1.3, 6.2.2, 6.2.3, 6.2.4, 6.2.4-1, 6.3.0, 6.3.0-1, 6.3.1, 6.4.0, 6.5.1, 6.6.0, 7.1.1, 7.4.0, 7.4.1, 7.5.0,
7.5.1, 7.5.2, 7.6.0, 7.6.1, 7.6.2, 7.7.0, 6.3.0.1, 0.1.0) to determine the most recent version due to incompatible
version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version
to install.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by maglub** [comment]
As a workaround, you can add the elastic role yourself through `ansible-galaxy role install -f -r requirements.yml elastic.elasticsearch

In your `requirements.yml` file:

```
- src: elastic.elasticsearch
  version: master
```
It is not a graylog issue, it is the elastic project that has a broken ansible galaxy repo.

**Comment by juju2112** [comment]
Yep, it seems to be related to:

https://github.com/elastic/ansible-elasticsearch/issues/538

**Comment by juju2112** [comment]
This should be fixed in master. Will update Ansible Galaxy once I get access to it.
