### ISSUE TITLE
Update Nginx dependency

### ISSUE THREAD

**Issue by juju2112** [Graylog2/graylog-ansible-role#144]
The Nginx role we have as a dependency has been abandoned:

https://github.com/jdauphant/ansible-role-nginx

I think this should be swapped out for the official Nginx Ansible role.

https://github.com/nginxinc/ansible-role-nginx

**Comment by filicivi** [comment]
Up for this.
The role **jdauphant.ansible-role-nginx** hasn't been updated in 2 years (according to ansible-galaxy) and is not fully-compatible with EL8 (it fails trying to install libselinux-python deps).

**Comment by juju2112** [comment]
I'm just going to remove `jdauphant.ansible-role-nginx` entirely. Graylog can install perfectly fine without it, and if someone wants Nginx, they can include the official Nginx role in their playbook themselves. 

I hope no one minds. It's been broken for months, anyway. 

@bernd
