### ISSUE TITLE
Add this role to Ansible Galaxy

### ISSUE THREAD

**Issue by ramondelafuente** [Graylog2/graylog-ansible-role#15]
Perhaps adding this role to Ansible Galaxy (basically just creating an account and pointing it to this repo) allows people to find it more easily? https://galaxy.ansible.com/

This role depends on our F500.elasticsearch role, and we (occasionally) get questions like these: https://github.com/f500/ansible-elasticsearch/issues/10

**Comment by danvaida** [comment]
https://galaxy.ansible.com/list#/roles/3162 :)

**Comment by ramondelafuente** [comment]
Hmm... that's odd... https://galaxy.ansible.com/list#/roles?page=1&per_page=10&sort_order=owner__username,name&f=greylog

**Comment by ramondelafuente** [comment]
Arrgg! Nevermind! I'm still sleeping. `e => a`
