### ISSUE TITLE
The 'graylog_mongodb_version' variable is not defined."

### ISSUE THREAD

**Issue by ryannix123** [Graylog2/graylog-ansible-role#154]
Hi,

The playbook works great except for one vexing issue that I can't figure out.

Everything works except I get this message at the end:

fatal: [192.168.0.203]: FAILED! => {"changed": false, "msg": "The 'graylog_mongodb_version' variable is not defined."}

I looked at graylog-ansible-role/defaults/main.yml and the version of Mongo does appear to be defined as 4.4

graylog_mongodb_version:                             4.4

What am I missing?

**Comment by juju2112** [comment]
What version of the code are you on? I see that default was added pretty recently. Is it possible it's set that way in Github, but not in your local copy?

You could just define it in your playbook.

**Comment by ryannix123** [comment]
Hi @juju2112 

As of Saturday, I was using the most recent release of the Graylog-Ansible repo, and everything worked perfectly except this one issue with deploying MongoDB. graylog-ansible-role/defaults/main.yml does seem to define it, though, so I'm not clear on where else it might be defined.

- Ryan

**Comment by nklmilojevic** [comment]
@juju2112 @ryannix123 when you fetch the role from ansible-galaxy it seems that it fetches the older version where mongodb version is not defined. If you clone the repo directly from GitHub, then it is okay.

**Comment by juju2112** [comment]
Alright. I tagged a new version and pushed it to Ansible Galaxy. Hopefully that should fix it.
