### ISSUE TITLE
Physical Nodes Installation

### ISSUE THREAD

**Issue by mmihir82** [Graylog2/graylog-ansible-role#156]
Hello, Like to install on physical multi nodes. How can I use your repo to install on physical nodes, instead VM.
Like to use 3 physical nodes all running Ubuntu. Can you help, how I can use your repo to install on physical nodes? 
Thank you

**Comment by juju2112** [comment]
That's really more of an Ansible question. It's not specifically related to this module. 

In general, you'd put the IP of the server into your hosts file and run Ansible against it. But I'd recommend reading up on the Ansible documentation. 

https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
