### ISSUE TITLE
uppercase/lowercase of the role name

### ISSUE THREAD

**Issue by roumano** [Graylog2/graylog-ansible-role#162]
Hi,

It's not a big issue but it's create some confusion :  
- [In galaxy](https://galaxy.ansible.com/Graylog2/graylog-ansible-role), the role is note as lowercase : **graylog2.graylog-ansible-role** ( `ansible-galaxy install graylog2.graylog-ansible-role` )
- [The real repo is in Uppercase](https://github.com/Graylog2/graylog-ansible-role)
- [Example in Readme](https://github.com/Graylog2/graylog-ansible-role/blob/master/README.md) are in Uppercase

So 
* if copy/passe the command line to install the role (`ansible-galaxy install graylog2.graylog-ansible-role` ), ansible-galaxy convert the role name from uppercase to lowercase : 
```
ansible-galaxy install graylog2.graylog-ansible-role
- downloading role 'graylog-ansible-role', owned by graylog2
- downloading role from https://github.com/Graylog2/graylog-ansible-role/archive/3.3.0.tar.gz
- extracting graylog2.graylog-ansible-role to /home/ddd/git/ansible/roles/graylog2.graylog-ansible-role
- graylog2.graylog-ansible-role (3.3.0) was installed successfully

```
* and try to use example, the role is not found as it's install in lowercase
```
ansible-playbook graylog.yml 
ERROR! the role 'Graylog2.graylog-ansible-role' was not found in /home/ddd/git/ansible/roles:/home/ddd/git/ansible/roles:/home/ddd/git/ansible

The error appears to be in '/home/ddd/git/ansible/graylog.yml': line 45, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: "Graylog2.graylog-ansible-role"
      ^ here

```

**Comment by juju2112** [comment]
Thanks @roumano. I fixed the example in the README.
