### ISSUE TITLE
Pass credentials of my own Elasticsearch and MongoDB server

### ISSUE THREAD

**Issue by arsalan993** [Graylog2/graylog-ansible-role#175]
I have setup a ES cluster on seperate node and a mongo cluster on seperate node. Both databases have a url and authenticated with username and password

Upon creating playbook how can i pass those variable 

here is official documentation there is method to pass ES username and pass along with host url 
https://github.com/Graylog2/graylog2-server/blob/7295064d0bff2973a927ccbc7726dd07cc2793f3/misc/graylog.conf#L172-L178

and for mongoDB it same .. 

but again how can pass these two variables through playbook without installing any new mongodb and elasticsearch .

**Comment by juju2112** [comment]
For the setting you mention in your link, that can be set by passing the `graylog_elasticsearch_hosts` var. There is also `graylog_mongodb_uri` for MongoDB.

This template here is what the Graylog settings file is built from:

https://github.com/Graylog2/graylog-ansible-role/blob/master/templates/graylog.server.conf.j2

If you need to configure a Graylog setting that isn't defined in one of our variables, you can do something like:

```
graylog_additional_config:
  elasticsearch_discovery_default_user: my_username
  elasticsearch_discovery_default_password: "{{ my_password }}"
```
