### ISSUE TITLE
Defaults can't be overwritten by vars

### ISSUE THREAD

**Issue by mputilin** [Graylog2/graylog-ansible-role#20]
Hello, 
in `tasks/prepare.yml` I've found
```
- name: Include distro-based vars
  include_vars: ../defaults/{{ ansible_distribution }}.yml
```
which overwrites roles or playbooks vars. Defaults has the lowest priority and mustn't be used in `include_vars`. Please, fix it.

**Comment by mariussturm** [comment]
Could you please elaborate what's your actual problem with this? It only overrides the graylog repo url, do you want to change that?

**Comment by mputilin** [comment]
yeah. I want to change version to latest (1.3)

**Comment by mariussturm** [comment]
It's set already to 1.3, have a look here: https://github.com/Graylog2/graylog-ansible-role/blob/master/defaults/Ubuntu.yml#L2

**Comment by mputilin** [comment]
please, update ansible galaxy version either

**Comment by mariussturm** [comment]
Done, thanks for the heads-up!
