### ISSUE TITLE
2.0.0 Incompatibilities

### ISSUE THREAD

**Issue by jamescarr** [Graylog2/graylog-ansible-role#22]
Unfortunately this breaks in 2.0.0 now due to a mis-formatted meta manifest in the mongodb dependency.

**Comment by jamescarr** [comment]
I opened a PR agains https://github.com/UnderGreen/ansible-role-mongodb/issues/37 in an attempt to resolve this.

**Comment by jamescarr** [comment]
That PR has been merged btw, might be able to update the dependencies now.

**Comment by mariussturm** [comment]
:+1: did you test the 2.0 branch of the `graylog-ansible-role` already? Should work now I guess.
