### ISSUE TITLE
Upgrade to 2.x

### ISSUE THREAD

**Issue by SystemZ** [Graylog2/graylog-ansible-role#24]
Hello, 
Is it safe to upgrade to 2.x branch with this ansible role?
Is any user intervention needed when I currently use 1.3.4 ?

**Comment by mariussturm** [comment]
There are alot of changes actually, please read this before https://github.com/Graylog2/graylog2-server/blob/master/UPGRADING.asciidoc

The Ansible role is not perfomaning any migration steps. So please review things like the MongoDB database name or Elasticsearch cluster name and things like that.
