### ISSUE TITLE
Feature Request: offer choice to install nginx from source

### ISSUE THREAD

**Issue by danvaida** [Graylog2/graylog-ansible-role#27]
Idea is to compile NGINX with `ngx_http_proxy_module` to be able to make use of `proxy_http_version: 1.1` so that you don't get 

> The response to this request is chunked and hence requires HTTP 1.1 to be sent, but this is a HTTP 1.0 request.

This happens when you want to export to CSV from within GL's web interface.

The choice of modules to be compiled should be given to the user, in the form of a list var. I'll try to submit a PR for this soon.

**Comment by juju2112** [comment]
Going to close this out since it's over 4 years old now.

I think for this role, we're going to focus on Graylog. Stuff like Nginx, Java, etc., we want other roles to handle that.
