### ISSUE TITLE
Make web_endpoint_uri configurable

### ISSUE THREAD

**Issue by pigulla** [Graylog2/graylog-ansible-role#35]
See the documentation [here](http://docs.graylog.org/en/2.0/pages/configuration/web_interface.html#configuring-webif).

This option is needed when using a reverse proxy and mapping the backend to a subdomain, e.g. using `example.com/api` instead of `example.com:12900`.

The `graylog_rest_transport_uri` variable is not sufficient to accomplish this.

**Comment by mariussturm** [comment]
There are some upcoming changes in the next 2.1 beta, I will change this when the final configuration is in the server.

**Comment by mariussturm** [comment]
This is fixed in 2.0.4
