### ISSUE TITLE
Make installation of Java optional

### ISSUE THREAD

**Issue by pigulla** [Graylog2/graylog-ansible-role#36]
It'd be nice if the installation of Java could be disabled (like with `graylog_install_nginx: false`).

In my particular case I'm deploying both Graylog and Icinga2 with Ansible. Graylog installs Oracle's Java 8 and Icinga installs the OpenJDK 7 (via its dependency to [geerlingguy.java](https://github.com/geerlingguy/ansible-role-java)), neither of which can be disabled.

**Comment by kroepke** [comment]
Graylog requires Java 8, it will not start with OpenJDK 7, not sure if making the requirement (because it is one) optional will make anything that much easier. But then again, I'm no ansible expert :)

**Comment by pigulla** [comment]
Aren't MongoDB and ElasticSearch also hard requirements? Installing those can be disabled, so I don't quite see your point.

**Comment by joschi** [comment]
@pigulla MongoDB and Elasticsearch could run on other systems. Java 8 is required to start Graylog and *must* be installed on the same system.

**Comment by pigulla** [comment]
@joschi Ah, indeed. So far I've had no trouble using the two JREs side by side, so feel free to close this.

**Comment by mariussturm** [comment]
When there is no actual problem I would not spend much time on this. However we are happy to receive pull request, so if you like that feature switch feel free to build it in.
