### ISSUE TITLE
node-id

### ISSUE THREAD

**Issue by suppix** [Graylog2/graylog-ansible-role#38]
Hello. 

After installation using ansible file /etc/graylog/server/node-id file is missing and graylog cant start up.

**Comment by mariussturm** [comment]
Hi,
the node-id file is created by the server itself, just make sure that the directory is writeable by the graylog user. At least on a Ubuntu system this works without interaction, how does your environment looks like?

**Comment by suppix** [comment]
Hello. 

I’m using debian jessie, fresh installation. 

ls -ald /etc/graylog/server
drwxr-xr-x 2 root root 4096 Aug 29 12:31 /etc/graylog/server

**Comment by mariussturm** [comment]
Fixed in 2.0.5!
