### ISSUE TITLE
Feature request: support for Centos/RHEL

### ISSUE THREAD

**Issue by bbaassssiiee** [Graylog2/graylog-ansible-role#39]
Many enterprises run on RedHat-based OS. Please add support for this in the role.

**Comment by bbaassssiiee** [comment]
1. Change dependency for MongoDB for RedHat/CentOS/Debian 64Bit:
https://galaxy.ansible.com/detail#/role/959

**Comment by swimlappy** [comment]
+1

**Comment by jalogisch** [comment]
only for the reference: https://github.com/Graylog2/graylog-ansible-role/pull/42 

We are waiting for one dependency Update to enable this.

**Comment by mohanrao** [comment]
Is this still open for the elastic PR to merged?

**Comment by mariussturm** [comment]
@mohanrao yes.

**Comment by bbaassssiiee** [comment]
We run this on Centos7. The elastic/ansible-elasticsearch role is pulled from Github. Once Elastic publishes their role on Galaxy it is a one line change to pull from there (but in essence it is the same thing.)
