### ISSUE TITLE
Cannot use with Ansible 1.9.4

### ISSUE THREAD

**Issue by alexbowers** [Graylog2/graylog-ansible-role#45]
ERROR: package is not a legal parameter in an Ansible task or handler

```
vagrant@hostname:/var/www/vhosts/mothership$ ansible --version
ansible 1.9.4
  configured module search path = None
```

Ansible file:

```
---
- hosts: all
  roles:
    - { role: graylog2.graylog }
```

**Comment by danvaida** [comment]
Any ansible version prior to 2.0 is not supported anymore. Docs should be updated.

**Comment by alexbowers** [comment]
The ansible role and ansible galaxy needs updating too, since it still says `min_ansible_version: 1.8`.

Is there a version I can use on an older ansible version?

**Comment by mariussturm** [comment]
Fixed here: https://github.com/Graylog2/graylog-ansible-role/commit/db8738cb6114d19a17030a3bddf4e9d7d67e79bd
