### ISSUE TITLE
Gzip defaults are wrong / mixed up

### ISSUE THREAD

**Issue by vascop** [Graylog2/graylog-ansible-role#46]
Here in: https://github.com/Graylog2/graylog-ansible-role/blob/f1fc74b7a826d8c74efe669ff0d28e301d656e26/templates/graylog.server.conf.j2#L53-L55
It's said that `web_enable_gzip` is enabled by default.

And here: https://github.com/Graylog2/graylog-ansible-role/blob/f1fc74b7a826d8c74efe669ff0d28e301d656e26/templates/graylog.server.conf.j2#L84-L86
It's said that `rest_enable_gzip` is disabled by default.

But looking in https://github.com/Graylog2/graylog-ansible-role/blob/f1fc74b7a826d8c74efe669ff0d28e301d656e26/defaults/main.yml
we can clearly see that it's actually the other way around, `graylog_rest_enable_gzip` defaults to true, and  `graylog_enable_gzip` defaults to false.

I don't know if the comments were the intended option or if the code was, so I can't really attach a PR.

**Comment by mariussturm** [comment]
Currently we need to disable gzip also on the rest port by default, till this fix arrived at most users: https://github.com/Graylog2/graylog2-server/pull/2894
Fixed in this commit:
https://github.com/Graylog2/graylog-ansible-role/commit/1a1387eb21f571ec8d8bb322155853cad69568a9
