### ISSUE TITLE
Support for OpenJDK 8

### ISSUE THREAD

**Issue by veger** [Graylog2/graylog-ansible-role#53]
I am willing to add support for OpenJDK 8 (comes with Ubuntu 16.04), next to the Orcale Java 8 support.

I'd like to know, as I don't want to unnecessary waste my time... ;)

**Comment by danvaida** [comment]
personally, I've had terrible experiences with openjdk (from a performance point of view)... I'd definitely recommend sticking with oraclejdk. choice is good, though.

**Comment by veger** [comment]
Ok. I have no experience with OpenJDK + Graylog.

I read that OpenJDK '[also works](http://docs.graylog.org/en/2.1/pages/installation.html)' and since we are using OpenJDK for other servers as well, I thought to install it on the Graylog cluster as well.

But if you do not recommend this, we'll leave it at this.

**Comment by mariussturm** [comment]
Yes, OpenJDK is officially supported by Graylog. However most production systems run with Oracle JDK. But to be on par with the Puppet and Chef cookbooks it would be a nice addition anyway.

**Comment by veger** [comment]
I agree about it being nice to have a choice.
But ATM I can not spend time on things that are not required for our deadline... Maybe later!
