### ISSUE TITLE
Travis testing fails on version: Version '8.1.1-2ubuntu0.2' for 'python-pip' was not found

### ISSUE THREAD

**Issue by bbaassssiiee** [Graylog2/graylog-ansible-role#59]
The Dockerfiles are explicit in the versions of everything. This creates a maintenance burden.

Please update in xenial.Dockerfile

**Comment by mariussturm** [comment]
Discussion was here: https://github.com/Graylog2/graylog-ansible-role/pull/55
@danvaida can you please take a look?

**Comment by mariussturm** [comment]
I guess this was fixed with PR#58, but personally I would also prefer to not pin versions until we actually need it. Especially when the versions are not actively maintained. Let's see how often this will reappear.

**Comment by bbaassssiiee** [comment]
It was not fixed with PR#58 as I don't have access to a  xenial system

**Comment by mariussturm** [comment]
Alright, fixed on master!
