### ISSUE TITLE
Understanding comment "use 2.x" graylog3 will be compatible and es_major_version 5.x

### ISSUE THREAD

**Issue by bronius** [Graylog2/graylog-ansible-role#78]
The README.md comment and ES version variables in
```
    # Graylog2 is not compatible with elasticsearch 5.x, so ensure to use 2.x (graylog3 will be compatible)
    # Also use version 0.2 of elastic.elasticsearch (ansible role), because vars are different
    es_major_version: "5.x"
```
from https://github.com/Graylog2/graylog-ansible-role/blob/2.3.0/README.md confuses me but makes sense in https://github.com/Graylog2/graylog-ansible-role/blob/2.2.3/README.md where it says:
```
    # Graylog2 is not compatible with elasticsearch 5.x, so ensure to use 2.x (graylog3 will be compatible)
    # Also use version 0.2 of elastic.elasticsearch (ansible role), because vars are different
    es_major_version: "2.x"
    es_version: "2.4.3"
```

Is Graylog3 actually Graylog2.3?  I think even Graylog2.3 is still referred to commonly as Graylog2, and no mention of Graylog3, proper, is out.

**Comment by joschi** [comment]
Elasticsearch 5.x is supported as of Graylog 2.3.0.

The README file is simply out-dated. ☹️

**Comment by mariussturm** [comment]
I hope this is more understandable now: https://github.com/Graylog2/graylog-ansible-role/commit/56b84570bfb6fbf7dadee2820a2abb926c4ec3f5

**Comment by bronius** [comment]
Excellent - thank you for tying up the loose ends :)
