### ISSUE TITLE
interactive auth needed for ES reload handler

### ISSUE THREAD

**Issue by JJWTimmer** [Graylog2/graylog-ansible-role#81]
Running the long example gives me below output against an Ubuntu 16.04 server. Is there anything i did wrong?

```
RUNNING HANDLER [elastic.elasticsearch : reload systemd configuration] *********12:49:58
541
fatal: [node01]: FAILED! => {"changed": true, "cmd": ["systemctl", "daemon-reload"], "delta": "0:00:00.007948", "end": "2018-01-31 11:49:59.168730", "msg": "non-zero return code", "rc": 1, "start": "2018-01-31 11:49:59.160782", "stderr": "Failed to execute operation: Interactive authentication required.", "stderr_lines": ["Failed to execute operation: Interactive authentication required."], "stdout": "", "stdout_lines": []}
542
```

**Comment by danvaida** [comment]
you probably need to escalate your privileges with sudo by inputting a password.
have you tried using “—become —ask-become-pass”?

**Comment by JJWTimmer** [comment]
Hmm, I'm running with AWX and all other steps needing sudo just work.
I use `import_role`, does that matter?

**Comment by JJWTimmer** [comment]
In the playbook I had become: true, and it was enough for most steps, but for this step I also had to enable Enable Privilege Escalation in AWX, now it works. Thanks.

**Comment by Nikolay0110** [comment]
I use the value: true in the playbook, turn on Enable Privilege Escalation in AWX and still the same error.
