### ISSUE TITLE
SELinux - only enable permission if SELInux is actually enabled

### ISSUE THREAD

**Issue by ColdIce1** [Graylog2/graylog-ansible-role#92]
With #87 SELinux stuff was added, but if SELinux is disabled, it fails to enable permissions for MongoDB.

Proposed fix:
` when: ansible_selinux.status == "enabled"`
Implies that facts are gathered during runtime.

**Comment by Oogy** [comment]
PR for this [here](https://github.com/Graylog2/graylog-ansible-role/pull/121).
