### ISSUE TITLE
Nginx version in requirements.yml

### ISSUE THREAD

**Issue by Fail-Unsafe** [Graylog2/graylog-ansible-role#94]
The Nginx version in requirements.yml is too old for newer Ansible versions and needs to be updated.

ERROR! 'always_run' is not a valid attribute for a Handler

The error appears to have been in '/home/username/ansible/roles/jdauphant.nginx/handlers/main.yml': line 17, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: check nginx configuration
  ^ here

This error can be suppressed as a warning using the "invalid_task_attribute_failed" configuration

**Comment by MegaGamesUkraine** [comment]
Have the same error
"ERROR! 'always_run' is not a valid attribute for a Handler

The error appears to have been in '/etc/ansible/roles/jdauphant.nginx/handlers/main.yml': line 17, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: check nginx configuration
  ^ here

This error can be suppressed as a warning using the "invalid_task_attribute_failed" configuration"
