### ISSUE TITLE
Missing configuration options

### ISSUE THREAD

**Issue by jokimaki** [Graylog2/graylog-ansible-role#96]
There seems to be quite a few configuration properties missing from graylog.server.conf.j2 compared to https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf.

In particular, I was looking for a way to set Elastisearch timeout parameters (http://docs.graylog.org/en/2.4/pages/configuration/server.conf.html#elasticsearch).

**Comment by Madnessy** [comment]
Also missing the disable version check option in the playbook (but also in the config file itself)

**Comment by juju2112** [comment]
You should be able to add in additional parameters like this:

```
    graylog_additional_config:
      test: value
```
